=== MrBartusek/MeteoalarmCard/src/translations/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "required": [
	  "$schema",
      "common",
      "error",
      "editor",
      "events",
      "messages"
  ],
  "properties": {
   	"$schema": {
			"$id": "#/properties/%24schema",
			"type": "string"
   	},
      "common": {
          "$id": "#/properties/common",
          "type": "object",
          "required": [
              "name",
              "description",
              "not_available"
          ],
          "properties": {
              "name": {
                  "$id": "#/properties/common/properties/name",
                  "type": ["string", "null"]
              },
              "description": {
                  "$id": "#/properties/common/properties/description",
                  "type": ["string", "null"]
              },
              "not_available": {
                  "$id": "#/properties/common/properties/not_available",
                  "type": ["string", "null"]
              }
          },
          "additionalProperties": false
      },
      "error": {
          "$id": "#/properties/error",
          "type": "object",
          "required": [
              "missing_entity",
              "missing_integration",
              "invalid_integration"
          ],
          "properties": {
              "missing_entity": {
                  "$id": "#/properties/error/properties/missing_entity",
                  "type": ["string", "null"]
              },
              "missing_integration": {
                  "$id": "#/properties/error/properties/missing_integration",
                  "type": ["string", "null"]
              },
              "invalid_integration": {
                  "$id": "#/properties/error/properties/invalid_integration",
                  "type": ["string", "null"]
              }
          },
          "additionalProperties": false
      },
      "editor": {
          "$id": "#/properties/editor",
          "type": "object",
          "required": [
              "entity",
              "integration",
              "required",
              "automatic",
              "recommended",
              "override_headline"
          ],
          "properties": {
              "entity": {
                  "$id": "#/properties/editor/properties/entity",
                  "type": ["string", "null"]
              },
              "integration": {
                  "$id": "#/properties/editor/properties/integration",
                  "type": ["string", "null"]
              },
              "required": {
                  "$id": "#/properties/editor/properties/required",
                  "type": ["string", "null"]
              },
              "automatic": {
                  "$id": "#/properties/editor/properties/automatic",
                  "type": ["string", "null"]
              },
              "recommended": {
                  "$id": "#/properties/editor/properties/recommended",
                  "type": ["string", "null"]
              },
              "override_headline": {
                "$id": "#/properties/editor/properties/override_headline",
                "type": ["string", "null"]
              }
          },
          "additionalProperties": false
      },
      "events": {
          "$id": "#/properties/events",
          "type": "object",
          "required": [
              "no_warnings",
              "wind",
              "snow_ice",
              "thunderstorms",
              "fog",
              "hight_temperature",
              "low_temperature",
              "coastal_event",
              "forest_fire",
              "avalanches",
              "rain",
              "flood",
              "rain_flood"
          ],
          "properties": {
              "no_warnings": {
                  "$id": "#/properties/events/properties/no_warnings",
                  "type": ["string", "null"]
              },
              "wind": {
                  "$id": "#/properties/events/properties/wind",
                  "type": ["string", "null"]
              },
              "snow_ice": {
                  "$id": "#/properties/events/properties/snow_ice",
                  "type": ["string", "null"]
              },
              "thunderstorms": {
                  "$id": "#/properties/events/properties/thunderstorms",
                  "type": ["string", "null"]
              },
              "fog": {
                  "$id": "#/properties/events/properties/fog",
                  "type": ["string", "null"]
              },
              "hight_temperature": {
                  "$id": "#/properties/events/properties/hight_temperature",
                  "type": ["string", "null"]
              },
              "low_temperature": {
                  "$id": "#/properties/events/properties/low_temperature",
                  "type": ["string", "null"]
              },
              "coastal_event": {
                  "$id": "#/properties/events/properties/coastal_event",
                  "type": ["string", "null"]
              },
              "forest_fire": {
                  "$id": "#/properties/events/properties/forest_fire",
                  "type": ["string", "null"]
              },
              "avalanches": {
                  "$id": "#/properties/events/properties/avalanches",
                  "type": ["string", "null"]
              },
              "rain": {
                  "$id": "#/properties/events/properties/rain",
                  "type": ["string", "null"]
              },
              "flood": {
                  "$id": "#/properties/events/properties/flood",
                  "type": ["string", "null"]
              },
              "rain_flood": {
                  "$id": "#/properties/events/properties/rain_flood",
                  "type": ["string", "null"]
              }
          },
          "additionalProperties": false
      },
      "messages": {
          "$id": "#/properties/messages",
          "type": "object",
          "required": [
              "yellow",
              "orange",
              "red"
          ],
          "properties": {
              "yellow": {
                  "$id": "#/properties/messages/properties/yellow",
                  "type": ["string", "null"]
              },
              "orange": {
                  "$id": "#/properties/messages/properties/orange",
                  "type": ["string", "null"]
              },
              "red": {
                  "$id": "#/properties/messages/properties/red",
                  "type": ["string", "null"]
              }
          },
          "additionalProperties": false
      }
  },
  "additionalProperties": false
}

=== MrBartusek/MeteoalarmCard/src/translations/nl.json
{
  "$schema": "./schema.json",
  "common": {
    "name": "Meteoalarm Kaart",
    "description": "Meteoalarm kaart waarschuwt u voor actuele weersomstandigheden.",
    "not_available": "Meteoalarm is niet beschikbaar"
  },
  "error": {
    "missing_entity": "Het specificeren van de entiteit is vereist!",
    "missing_integration": "Het specificeren van de entiteit is vereist!",
    "invalid_integration": "Deze integratie is niet geldig!"
  },
  "editor": {
    "entity": "Entiteit",
    "integration": "Integratie",
    "required": "Verplicht",
    "automatic": "Automatisch",
    "recommended": "Aanbevolen",
    "override_headline": "Koptekst overschrijven"
  },
  "events": {
    "no_warnings": "Geen waarschuwingen",
    "wind": "wind",
    "snow_ice": "sneeuw/ijzel/bevriezing",
    "thunderstorms": "onweer",
    "fog": "mist",
    "hight_temperature": "hitte",
    "low_temperature": "koude",
    "coastal_event": "kustbedreiging",
    "forest_fire": "bos- en heidebranden",
    "avalanches": "lawines",
    "rain": "regen",
    "flood": "hoogwater",
    "rain_flood": "wateroverlast"
  },
  "messages": {
    "yellow": "Waarschuwing geel {0}",
    "orange": "Waarschuwing oranje {0}",
    "red": "Waarschuwing rood {0}"
  }
}
