=== MrBartusek/MeteoalarmCard/src/localize/schema/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "required": [
        "$schema",
        "common",
        "error",
        "editor",
        "events",
        "messages"
    ],
    "properties": {
         "$schema": {
              "$id": "#/properties/%24schema",
              "type": "string"
         },
        "common": {
            "$id": "#/properties/common",
            "type": "object",
            "required": [
                "name",
                "description",
                "warning",
                "expected",
                "unavailable"
            ],
            "properties": {
                "name": {
                    "$id": "#/properties/common/properties/name",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/common/description",
                    "type": ["string", "null"]
                },
                "warning": {
                    "$id": "#/properties/common/warning",
                    "type": ["string", "null"]
                },
                "expected": {
                    "$id": "#/properties/common/expected",
                    "type": ["string", "null"]
                },
                "unavailable": {
                    "$id": "#/properties/common/properties/description/unavailable",
                    "type": "object",
                    "required": [
                        "long",
                        "short"
                    ],
                    "properties": {
                        "long": {
                            "$id": "#/properties/common/properties/description/unavailable/properties/long",
                            "type": ["string", "null"]
                        },
                        "short": {
                            "$id": "#/properties/common/properties/description/unavailable/properties/long",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "error": {
            "$id": "#/properties/error",
            "type": "object",
            "required": [
                "missing_entity",
                "invalid_integration",
                "invalid_scaling_mode",
                "entity_invalid"
            ],
            "properties": {
                "missing_entity": {
                    "$id": "#/properties/error/properties/missing_entity",
                    "type": ["string", "null"]
                },
                "invalid_integration": {
                    "$id": "#/properties/error/properties/invalid_integration",
                    "type": ["string", "null"]
                },
                "invalid_scaling_mode": {
                    "$id": "#/properties/error/properties/invalid_scaling_mode",
                    "type": ["string", "null"]
                },
                "entity_invalid": {
                    "$id": "#/properties/common/properties/entity_invalid",
                    "type": "object",
                    "required": [
                        "single",
                        "multiple"
                    ],
                    "properties": { 
                        "single": {
                            "$id": "#/properties/error/properties/entity_invalid/single",
                            "type": ["string", "null"]
                        },
                        "multiple": {
                            "$id": "#/properties/error/properties/entity_invalid/multiple",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "editor": {
            "$id": "#/properties/editor",
            "type": "object",
            "required": [
                "entity",
                "integration",
                "required",
                "recommended",
                "override_headline",
                "hide_when_no_warning",
                "hide_caption",
                "disable_swiper",
                "description",
                "error",
                "scaling_mode",
                "scaling_mode_options"
            ],
            "properties": {
                "entity": {
                    "$id": "#/properties/editor/properties/entity",
                    "type": ["string", "null"]
                },
                "integration": {
                    "$id": "#/properties/editor/properties/integration",
                    "type": ["string", "null"]
                },
                "required": {
                    "$id": "#/properties/editor/properties/required",
                    "type": ["string", "null"]
                },
                "recommended": {
                    "$id": "#/properties/editor/properties/recommended",
                    "type": ["string", "null"]
                },
                "override_headline": {
                  "$id": "#/properties/editor/properties/override_headline",
                  "type": ["string", "null"]
                },
                "hide_when_no_warning": {
                    "$id": "#/properties/editor/properties/hide_when_no_warning",
                    "type": ["string", "null"]
                },
                "hide_caption": {
                    "$id": "#/properties/editor/properties/hide_caption",
                    "type": ["string", "null"]
                },
                "disable_swiper": {
                    "$id": "#/properties/editor/properties/disable_swiper",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/editor/properties/description",
                    "type": "object",
                    "required": [
                        "start",
                        "current_expected",
                        "slots",
                        "separate_events",
                        "warning_watch_statement",
                        "end"
                    ],
                    "properties": { 
                        "start": {
                            "$id": "#/properties/editor/properties/description/start",
                            "type": ["string", "null"]
                        },
                        "current_expected": {
                            "$id": "#/properties/editor/properties/description/current_expected",
                            "type": ["string", "null"]
                        },
                        "slots": {
                            "$id": "#/properties/editor/properties/description/slots",
                            "type": ["string", "null"]
                        },
                        "separate_events": {
                            "$id": "#/properties/editor/properties/description/separate_events",
                            "type": ["string", "null"]
                        },
                        "warning_watch_statement": {
                            "$id": "#/properties/editor/properties/description/warning_watch_statement",
                            "type": ["string", "null"]
                        },
                        "end": {
                            "$id": "#/properties/editor/properties/description/end",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "error": {
                    "$id": "#/properties/editor/properties/error",
                    "type": "object",
                    "required": [
                        "expected_entity",
                        "too_many_entities",
                        "duplicate"
                    ],
                    "properties": { 
                        "expected_entity": {
                            "$id": "#/properties/editor/properties/error/expected_entity",
                            "type": ["string", "null"]
                        },
                        "too_many_entities": {
                            "$id": "#/properties/editor/properties/error/too_many_entities",
                            "type": ["string", "null"]
                        },
                        "duplicate": {
                            "$id": "#/properties/editor/properties/duplicate/",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "scaling_mode": {
                    "$id": "#/properties/editor/properties/scaling_mode",
                    "type": ["string", "null"]
                },
                "scaling_mode_options": {
                    "$id": "#/properties/scaling_mode_options",
                    "type": "object",
                    "required": [
                        "disabled",
                        "headline",
                        "scale",
                        "headline_and_scale"
                    ],
                    "properties": {
                        "disabled": {
                            "$id": "#/properties/editor/properties/disabled",
                            "type": ["string", "null"]
                        },
                        "headline": {
                            "$id": "#/properties/editor/properties/headline",
                            "type": ["string", "null"]
                        },
                        "scale": {
                            "$id": "#/properties/editor/properties/scale",
                            "type": ["string", "null"]
                        },
                        "headline_and_scale": {
                            "$id": "#/properties/editor/properties/headline_and_scale",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "events": {
            "$id": "#/properties/events",
            "type": "object",
            "required": [
                "no_warnings",
                "nuclear",
                "hurricane",
                "wind",
                "snow_ice",
                "thunderstorms",
                "fog",
                "high_temperature",
                "low_temperature",
                "coastal_event",
                "sea_event",
                "forest_fire",
                "avalanches",
                "earthquake",
                "volcano",
                "rain",
                "flooding",
                "tornado",
                "air_quality",
                "dust"
            ],
            "properties": {
                "no_warnings": {
                    "$id": "#/properties/events/properties/no_warnings",
                    "type": ["string", "null"]
                },
                "nuclear": {
                    "$id": "#/properties/events/properties/nuclear",
                    "type": ["string", "null"]
                },
                "hurricane": {
                    "$id": "#/properties/events/properties/hurricane",
                    "type": ["string", "null"]
                },
                "wind": {
                    "$id": "#/properties/events/properties/wind",
                    "type": ["string", "null"]
                },
                "snow_ice": {
                    "$id": "#/properties/events/properties/snow_ice",
                    "type": ["string", "null"]
                },
                "thunderstorms": {
                    "$id": "#/properties/events/properties/thunderstorms",
                    "type": ["string", "null"]
                },
                "fog": {
                    "$id": "#/properties/events/properties/fog",
                    "type": ["string", "null"]
                },
                "high_temperature": {
                    "$id": "#/properties/events/properties/high_temperature",
                    "type": ["string", "null"]
                },
                "low_temperature": {
                    "$id": "#/properties/events/properties/low_temperature",
                    "type": ["string", "null"]
                },
                "coastal_event": {
                    "$id": "#/properties/events/properties/coastal_event",
                    "type": ["string", "null"]
                },
                "sea_event": {
                    "$id": "#/properties/events/properties/sea_event",
                    "type": ["string", "null"]
                },
                "forest_fire": {
                    "$id": "#/properties/events/properties/forest_fire",
                    "type": ["string", "null"]
                },
                "avalanches": {
                    "$id": "#/properties/events/properties/avalanches",
                    "type": ["string", "null"]
                },
                "earthquake": {
                    "$id": "#/properties/events/properties/earthquake",
                    "type": ["string", "null"]
                },
                "volcano": {
                    "$id": "#/properties/events/properties/volcano",
                    "type": ["string", "null"]
                },
                "rain": {
                    "$id": "#/properties/events/properties/rain",
                    "type": ["string", "null"]
                },
                "flooding": {
                    "$id": "#/properties/events/properties/flooding",
                    "type": ["string", "null"]
                },
                "tornado": {
                    "$id": "#/properties/events/properties/tornado",
                    "type": ["string", "null"]
                },
                "air_quality": {
                    "$id": "#/properties/events/properties/air_quality",
                    "type": ["string", "null"]
                },
                "dust": {
                    "$id": "#/properties/events/properties/air_quality",
                    "type": ["string", "null"]
                },
                "tsunami": {
                    "$id": "#/properties/events/properties/tsunami",
                    "type": ["string", "null"]
                }
            },
            "additionalProperties": false
        },
        "messages": {
            "$id": "#/properties/messages",
            "type": "object",
            "required": [
                "yellow",
                "orange",
                "red"
            ],
            "properties": {
                "yellow": {
                    "$id": "#/properties/messages/properties/yellow",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/error/properties/messages/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/error/properties/messages/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/error/properties/messages/color",
                          "type": ["string", "null"]
                      },
                      "additionalProperties": false
                    }
                },
                "orange": {
                    "$id": "#/properties/messages/properties/orange",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/error/properties/messages/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/error/properties/messages/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/error/properties/messages/color",
                          "type": ["string", "null"]
                      },
                      "additionalProperties": false
                    }
                },
                "red": {
                    "$id": "#/properties/messages/properties/red",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/error/properties/messages/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/error/properties/messages/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/error/properties/messages/color",
                          "type": ["string", "null"]
                      },
                      "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}

=== MrBartusek/MeteoalarmCard/src/localize/languages/es.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Tarjeta Meteoalarm",
    "description": "La tarjeta Meteoalarm le advierte sobre eventos meteorológicos actuales.",
    "warning": "Aviso",
    "expected": "Esperado",
    "unavailable": {
      "long": "La integración no está disponible",
      "short": "No disponible"
    }
  },
  "error": {
    "missing_entity": "¡Se requiere especificar la entidad!",
    "invalid_integration": "¡Esta integración no es válida!",
    "invalid_scaling_mode": null,
    "entity_invalid": {
      "single": "La integración seleccionada no coincide con la entidad seleccionada.",
      "multiple": "La integración seleccionada no coincide con las entidades seleccionadas: {entity}."
    }
  },
  "editor": {
    "entity": "Entidad",
    "integration": "Integración",
    "required": "Necesario",
    "recommended": "Recomendado",
    "override_headline": "Sobreescribir cabecera",
    "hide_when_no_warning": "Ocultar cuando no hay avisos",
    "hide_caption": "Ocultar título",
    "disable_swiper": "Deshabilitar el deslizador de alertas",
    "description": {
      "start": "La integración seleccionada crea múltiples entidades.",
      "current_expected": "El primero con los eventos actuales y el segundo con los futuros.",
      "slots": "La cantidad exacta creada está determinada por su configuración.",
      "separate_events": "Cada tipo de evento tiene una entidad separada.",
      "warning_watch_statement": "Hay 3 entidades: avisos, alertas y declaraciones.",
      "end": "Debes agregarlos todos para asegurarte de no perderte ninguna alerta."
    },
    "error": {
      "expected_entity": "No se ha proporcionado la entidad de avisos esperada. No se mostrarán futuros eventos.",
      "too_many_entities": "No se han proporcionado más entidades de las esperadas. Esperaba {expected} entidades, obtuve {obtuve} entidades.",
      "duplicate": "Encontrados duplicados en la lista de entidades."
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    }
  },
  "events": {
    "no_warnings": "Sin avisos",
    "nuclear": "evento nuclear",
    "tornado": "tornado",
    "hurricane": "huracán",
    "wind": "viento",
    "earthquake": "terremoto",
    "volcano": "volcán",
    "snow_ice": "nieve/hielo",
    "fog": "niebla",
    "high_temperature": "alta temperatura",
    "low_temperature": "baja temperatura",
    "coastal_event": "fenómeno costero",
    "tsunami": "tsunami",
    "sea_event": "evento marino",
    "forest_fire": "incendio forestal",
    "avalanches": "aludes",
    "thunderstorms": "tormentas",
    "rain": "lluvia",
    "flooding": "inundación",
    "air_quality": "calidad del aire",
    "dust": "polvo"
  },
  "messages": {
    "yellow": {
      "event": "Alerta amarilla por {event}",
      "generic": "Alerta amarilla",
      "color": "Amarillo"
    },
    "orange": {
      "event": "Alerta naranja por {event}",
      "generic": "Alerta naranja",
      "color": "Naranja"
    },
    "red": {
      "event": "Alerta roja por {event}",
      "generic": "Alerta roja",
      "color": "Rojo"
    }
  }
}

=== MrBartusek/MeteoalarmCard/src/localize/languages/pl.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Karta Meteoalarm",
    "description": "Meteoalarm ostrzega cię przed aktualnymi zdarzeniami pogodowymi.",
    "warning": "Ostrzeżenie",
    "expected": "Spodziewane",
    "unavailable": {
      "long": "Integracja nie jest dostępna",
      "short": "Niedostępny"
    }
  },
  "error": {
    "missing_entity": "Podanie encji jest wymagane!",
    "invalid_integration": "Nieprawidłowa integracja!",
    "invalid_scaling_mode": null,
    "entity_invalid": {
      "single": "Wybrana integracja nie opdowiada wybranej encji.",
      "multiple": "Wybrana integracja nie odpowiada wybranym encjom: {entity}."
    }
  },
  "editor": {
    "entity": "Encja",
    "integration": "Integracja",
    "required": "Wymagane",
    "recommended": "Zalecane",
    "override_headline": "Nadpisz nagłówek",
    "hide_when_no_warning": "Ukryj kiedy nie ma ostrzeżeń",
    "hide_caption": "Ukryj podpis",
    "disable_swiper": "Wyłacz swiper ostrzeżeń",
    "description": {
      "start": "Wybrana integracja tworzy kilka encji.",
      "current_expected": "Pierwszą z aktualnymi zdarzeniami a drugą z przyszłymi.",
      "slots": "Dokładna ilość określana jest przez jej konfiguracje.",
      "separate_events": "Każde ostrzeżenie ma swoją własną encję",
      "warning_watch_statement": "Tworzone sa 3 encje: warnings, watches i statements.",
      "end": "Powinieneś dodać wszystkie encje aby mieć pewność że nie przegapisz żadnych ostrzeżeń."
    },
    "error": {
      "expected_entity": "Nie podano encji z przyszłymi zdarzeniami pogodowymi. Pryszłe ostrzeżenia nie bedą pokazywane.",
      "too_many_entities": "Podano więcej encji niż się spodziewano. Spodziewano: {expected} encji, otrzymano {got} encji.",
      "duplicate": "Znaleziono duplikaty w liście encji."
    },
    "scaling_mode": "Tryb skalowania",
    "scaling_mode_options": {
      "disabled": "Wyłaczony",
      "headline": "Tylko Nagłówek",
      "scale": "Tylko Skala",
      "headline_and_scale": "Nagłówek i skala"
    }
  },
  "events": {
    "no_warnings": "Brak ostrzeżeń",
    "nuclear": "nuklearne",
    "tornado": "tornado",
    "hurricane": "huragan",
    "wind": "wiatr",
    "earthquake": "trzęsienie ziemi",
    "volcano": "aktywność wulkaniczna",
    "snow_ice": "śnieg/oblodzenie",
    "fog": "mgły",
    "high_temperature": "wysoka temperatura",
    "low_temperature": "silne mrozy",
    "coastal_event": "zjawiska strefy brzegowej",
    "tsunami": "tsunami",
    "sea_event": "wydarzenie na morzu",
    "forest_fire": "pożary lasu",
    "avalanches": "lawiny",
    "thunderstorms": "burze",
    "rain": "deszcz",
    "flooding": "powodzie",
    "air_quality": "jakość powietrza",
    "dust": "pył"
  },
  "messages": {
    "yellow": {
      "event": "Żółty alert na {event}",
      "generic": "Żółty alert",
      "color": "Żółty"
    },
    "orange": {
      "event": "Pomarańczowy alert na {event}",
      "generic": "Pomarańczowy alert",
      "color": "Pomarańczowy"
    },
    "red": {
      "event": "Czerwony alert na {event}",
      "generic": "Czerwony alert",
      "color": "Czerwony"
    }
  }
}

=== MrBartusek/MeteoalarmCard/src/localize/languages/et.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Ohtlike ilmanähtuste kaart",
    "description": "Äärmuslike ilmaolude hoiatus.",
    "warning": null,
    "expected": null,
    "unavailable": {
      "long": "Olem pole saadaval",
      "short": "Pole saadaval"
    }
  },
  "error": {
    "missing_entity": "Vajalik on Meteoalarmi olem!",
    "invalid_integration": "Meteoalarmi sidumine on vale!",
    "invalid_scaling_mode": null,
    "entity_invalid": {
      "single": null,
      "multiple": null
    }
  },
  "editor": {
    "entity": "Olem",
    "integration": "Sidumine",
    "required": "Nõutav",
    "recommended": "Soovituslik",
    "override_headline": "Pealdise alistamine",
    "hide_when_no_warning": "Hoiatuste puudumisel peida kaart",
    "hide_caption": null,
    "disable_swiper": null,
    "description": {
      "start": null,
      "current_expected": null,
      "slots": null,
      "separate_events": null,
      "warning_watch_statement": null,
      "end": null
    },
    "error": {
      "expected_entity": null,
      "too_many_entities": null,
      "duplicate": null
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    }
  },
  "events": {
    "no_warnings": "Hoiatusi hetkel pole",
    "nuclear": null,
    "tornado": null,
    "hurricane": null,
    "wind": "tugev tuul",
    "earthquake": null,
    "volcano": null,
    "snow_ice": "lumi või jää",
    "fog": "udu",
    "high_temperature": null,
    "low_temperature": "külmalaine",
    "coastal_event": "rannikumeri",
    "tsunami": null,
    "sea_event": null,
    "forest_fire": "metsapõleng",
    "avalanches": "laviin",
    "thunderstorms": "äike",
    "rain": "sademed",
    "flooding": null,
    "air_quality": null,
    "dust": null
  },
  "messages": {
    "yellow": {
      "event": "Kollane hoiatus {event}",
      "generic": "Kollane hoiatus",
      "color": "Kollane"
    },
    "orange": {
      "event": "Oranž hoiatus {event}",
      "generic": "Oranž hoiatus",
      "color": "Oranž"
    },
    "red": {
      "event": "Punane hoiatus {event}",
      "generic": "Punane hoiatus",
      "color": "Punane"
    }
  }
}

=== MrBartusek/MeteoalarmCard/src/localize/languages/cs.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Meteoalarm Card",
    "description": "Meteoalarm karta zobrazuje aktuální meteorologické výstrahy v okolí.",
    "warning": "Varování",
    "expected": "Očekávané",
    "unavailable": {
      "long": "Meteoalarm není dostupný",
      "short": "Není k dispozici"
    }
  },
  "error": {
    "missing_entity": "Entita je povinná!",
    "invalid_integration": "Integrace není validní!",
    "invalid_scaling_mode": null,
    "entity_invalid": {
      "single": "Vybraná integrace se neshoduje s entitou",
      "multiple": "Vybraná integrace se neshoduje s entitami: {entity}"
    }
  },
  "editor": {
    "entity": "Entita",
    "integration": "Integrace",
    "required": "Povinné",
    "recommended": "Doporučeno",
    "override_headline": "Přepsat nadpis",
    "hide_when_no_warning": "Skrýt, pokud nejsou žádná varování",
    "hide_caption": "Skrýt popis",
    "disable_swiper": "Zakázat swipování",
    "description": {
      "start": null,
      "current_expected": null,
      "slots": null,
      "separate_events": null,
      "warning_watch_statement": null,
      "end": null
    },
    "error": {
      "expected_entity": "Nenalezena entita. Budoucí události nebudou zobrazeny.",
      "too_many_entities": "Nalezeno více entit než bylo očekáváno. Očekáváno: {expected} entit, nalezeno {got} entit.",
      "duplicate": "Nalezeny duplikáty v seznamu entit."
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    }
  },
  "events": {
    "no_warnings": "Žádné varování",
    "nuclear": "jaderná událost",
    "tornado": "tornádo",
    "hurricane": "hurikán",
    "wind": "vítr",
    "earthquake": "zemětřesení",
    "volcano": "sopečná činnost",
    "snow_ice": "sníh/led",
    "fog": "mlha",
    "high_temperature": "extrémně vysoké teploty",
    "low_temperature": "extrémně nízké teploty",
    "coastal_event": "pobřežní událost",
    "tsunami": "tsunami",
    "sea_event": "mořská událost",
    "forest_fire": "lesní požáry",
    "avalanches": "laviny",
    "thunderstorms": "bouřky",
    "rain": "déšť",
    "flooding": "povodeň",
    "air_quality": "kvalita vzduchu",
    "dust": "pyl"
  },
  "messages": {
    "yellow": {
      "event": "Žluté {event} varování",
      "generic": "Žluté varování",
      "color": "Žluté"
    },
    "orange": {
      "event": "Oranžové {event} varování",
      "generic": "Oranžové varování",
      "color": "Oranžové"
    },
    "red": {
      "event": "Červené {event} varování",
      "generic": "Červené varování",
      "color": "Červené"
    }
  }
}
