=== MrBartusek/MeteoalarmCard/src/localize/schema/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "required": [
        "$schema",
        "common",
        "error",
        "editor",
        "events",
        "messages"
    ],
    "properties": {
         "$schema": {
              "$id": "#/properties/%24schema",
              "type": "string"
         },
        "common": {
            "$id": "#/properties/common",
            "type": "object",
            "required": [
                "name",
                "description",
                "warning",
                "expected",
                "unavailable"
            ],
            "properties": {
                "name": {
                    "$id": "#/properties/common/properties/name",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/common/description",
                    "type": ["string", "null"]
                },
                "warning": {
                    "$id": "#/properties/common/warning",
                    "type": ["string", "null"]
                },
                "expected": {
                    "$id": "#/properties/common/expected",
                    "type": ["string", "null"]
                },
                "unavailable": {
                    "$id": "#/properties/common/properties/description/unavailable",
                    "type": "object",
                    "required": [
                        "long",
                        "short"
                    ],
                    "properties": {
                        "long": {
                            "$id": "#/properties/common/properties/description/unavailable/properties/long",
                            "type": ["string", "null"]
                        },
                        "short": {
                            "$id": "#/properties/common/properties/description/unavailable/properties/long",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "error": {
            "$id": "#/properties/error",
            "type": "object",
            "required": [
                "missing_entity",
                "invalid_integration",
                "invalid_scaling_mode",
                "entity_invalid"
            ],
            "properties": {
                "missing_entity": {
                    "$id": "#/properties/error/properties/missing_entity",
                    "type": ["string", "null"]
                },
                "invalid_integration": {
                    "$id": "#/properties/error/properties/invalid_integration",
                    "type": ["string", "null"]
                },
                "invalid_scaling_mode": {
                    "$id": "#/properties/error/properties/invalid_scaling_mode",
                    "type": ["string", "null"]
                },
                "entity_invalid": {
                    "$id": "#/properties/common/properties/entity_invalid",
                    "type": "object",
                    "required": [
                        "single",
                        "multiple"
                    ],
                    "properties": { 
                        "single": {
                            "$id": "#/properties/error/properties/entity_invalid/single",
                            "type": ["string", "null"]
                        },
                        "multiple": {
                            "$id": "#/properties/error/properties/entity_invalid/multiple",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "editor": {
            "$id": "#/properties/editor",
            "type": "object",
            "required": [
                "entity",
                "integration",
                "required",
                "recommended",
                "override_headline",
                "hide_when_no_warning",
                "hide_caption",
                "disable_swiper",
                "description",
                "error",
                "scaling_mode",
                "scaling_mode_options"
            ],
            "properties": {
                "entity": {
                    "$id": "#/properties/editor/properties/entity",
                    "type": ["string", "null"]
                },
                "integration": {
                    "$id": "#/properties/editor/properties/integration",
                    "type": ["string", "null"]
                },
                "required": {
                    "$id": "#/properties/editor/properties/required",
                    "type": ["string", "null"]
                },
                "recommended": {
                    "$id": "#/properties/editor/properties/recommended",
                    "type": ["string", "null"]
                },
                "override_headline": {
                  "$id": "#/properties/editor/properties/override_headline",
                  "type": ["string", "null"]
                },
                "hide_when_no_warning": {
                    "$id": "#/properties/editor/properties/hide_when_no_warning",
                    "type": ["string", "null"]
                },
                "hide_caption": {
                    "$id": "#/properties/editor/properties/hide_caption",
                    "type": ["string", "null"]
                },
                "disable_swiper": {
                    "$id": "#/properties/editor/properties/disable_swiper",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/editor/properties/description",
                    "type": "object",
                    "required": [
                        "start",
                        "current_expected",
                        "slots",
                        "separate_events",
                        "warning_watch_statement",
                        "end"
                    ],
                    "properties": { 
                        "start": {
                            "$id": "#/properties/editor/properties/description/start",
                            "type": ["string", "null"]
                        },
                        "current_expected": {
                            "$id": "#/properties/editor/properties/description/current_expected",
                            "type": ["string", "null"]
                        },
                        "slots": {
                            "$id": "#/properties/editor/properties/description/slots",
                            "type": ["string", "null"]
                        },
                        "separate_events": {
                            "$id": "#/properties/editor/properties/description/separate_events",
                            "type": ["string", "null"]
                        },
                        "warning_watch_statement": {
                            "$id": "#/properties/editor/properties/description/warning_watch_statement",
                            "type": ["string", "null"]
                        },
                        "end": {
                            "$id": "#/properties/editor/properties/description/end",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "error": {
                    "$id": "#/properties/editor/properties/error",
                    "type": "object",
                    "required": [
                        "expected_entity",
                        "too_many_entities",
                        "duplicate"
                    ],
                    "properties": { 
                        "expected_entity": {
                            "$id": "#/properties/editor/properties/error/expected_entity",
                            "type": ["string", "null"]
                        },
                        "too_many_entities": {
                            "$id": "#/properties/editor/properties/error/too_many_entities",
                            "type": ["string", "null"]
                        },
                        "duplicate": {
                            "$id": "#/properties/editor/properties/duplicate/",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "scaling_mode": {
                    "$id": "#/properties/editor/properties/scaling_mode",
                    "type": ["string", "null"]
                },
                "scaling_mode_options": {
                    "$id": "#/properties/scaling_mode_options",
                    "type": "object",
                    "required": [
                        "disabled",
                        "headline",
                        "scale",
                        "headline_and_scale"
                    ],
                    "properties": {
                        "disabled": {
                            "$id": "#/properties/editor/properties/disabled",
                            "type": ["string", "null"]
                        },
                        "headline": {
                            "$id": "#/properties/editor/properties/headline",
                            "type": ["string", "null"]
                        },
                        "scale": {
                            "$id": "#/properties/editor/properties/scale",
                            "type": ["string", "null"]
                        },
                        "headline_and_scale": {
                            "$id": "#/properties/editor/properties/headline_and_scale",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "events": {
            "$id": "#/properties/events",
            "type": "object",
            "required": [
                "no_warnings",
                "nuclear",
                "hurricane",
                "wind",
                "snow_ice",
                "thunderstorms",
                "fog",
                "high_temperature",
                "low_temperature",
                "coastal_event",
                "sea_event",
                "forest_fire",
                "avalanches",
                "earthquake",
                "volcano",
                "rain",
                "flooding",
                "tornado",
                "air_quality",
                "dust"
            ],
            "properties": {
                "no_warnings": {
                    "$id": "#/properties/events/properties/no_warnings",
                    "type": ["string", "null"]
                },
                "nuclear": {
                    "$id": "#/properties/events/properties/nuclear",
                    "type": ["string", "null"]
                },
                "hurricane": {
                    "$id": "#/properties/events/properties/hurricane",
                    "type": ["string", "null"]
                },
                "wind": {
                    "$id": "#/properties/events/properties/wind",
                    "type": ["string", "null"]
                },
                "snow_ice": {
                    "$id": "#/properties/events/properties/snow_ice",
                    "type": ["string", "null"]
                },
                "thunderstorms": {
                    "$id": "#/properties/events/properties/thunderstorms",
                    "type": ["string", "null"]
                },
                "fog": {
                    "$id": "#/properties/events/properties/fog",
                    "type": ["string", "null"]
                },
                "high_temperature": {
                    "$id": "#/properties/events/properties/high_temperature",
                    "type": ["string", "null"]
                },
                "low_temperature": {
                    "$id": "#/properties/events/properties/low_temperature",
                    "type": ["string", "null"]
                },
                "coastal_event": {
                    "$id": "#/properties/events/properties/coastal_event",
                    "type": ["string", "null"]
                },
                "sea_event": {
                    "$id": "#/properties/events/properties/sea_event",
                    "type": ["string", "null"]
                },
                "forest_fire": {
                    "$id": "#/properties/events/properties/forest_fire",
                    "type": ["string", "null"]
                },
                "avalanches": {
                    "$id": "#/properties/events/properties/avalanches",
                    "type": ["string", "null"]
                },
                "earthquake": {
                    "$id": "#/properties/events/properties/earthquake",
                    "type": ["string", "null"]
                },
                "volcano": {
                    "$id": "#/properties/events/properties/volcano",
                    "type": ["string", "null"]
                },
                "rain": {
                    "$id": "#/properties/events/properties/rain",
                    "type": ["string", "null"]
                },
                "flooding": {
                    "$id": "#/properties/events/properties/flooding",
                    "type": ["string", "null"]
                },
                "tornado": {
                    "$id": "#/properties/events/properties/tornado",
                    "type": ["string", "null"]
                },
                "air_quality": {
                    "$id": "#/properties/events/properties/air_quality",
                    "type": ["string", "null"]
                },
                "dust": {
                    "$id": "#/properties/events/properties/air_quality",
                    "type": ["string", "null"]
                },
                "tsunami": {
                    "$id": "#/properties/events/properties/tsunami",
                    "type": ["string", "null"]
                }
            },
            "additionalProperties": false
        },
        "messages": {
            "$id": "#/properties/messages",
            "type": "object",
            "required": [
                "yellow",
                "orange",
                "red"
            ],
            "properties": {
                "yellow": {
                    "$id": "#/properties/messages/properties/yellow",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/error/properties/messages/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/error/properties/messages/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/error/properties/messages/color",
                          "type": ["string", "null"]
                      },
                      "additionalProperties": false
                    }
                },
                "orange": {
                    "$id": "#/properties/messages/properties/orange",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/error/properties/messages/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/error/properties/messages/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/error/properties/messages/color",
                          "type": ["string", "null"]
                      },
                      "additionalProperties": false
                    }
                },
                "red": {
                    "$id": "#/properties/messages/properties/red",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/error/properties/messages/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/error/properties/messages/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/error/properties/messages/color",
                          "type": ["string", "null"]
                      },
                      "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}

=== MrBartusek/MeteoalarmCard/src/localize/languages/nl.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Meteoalarm Kaart",
    "description": "Meteoalarm kaart waarschuwt u voor actuele weersomstandigheden.",
    "warning": null,
    "expected": null,
    "unavailable": {
      "long": null,
      "short": null
    }
  },
  "error": {
    "missing_entity": "Het specificeren van de entiteit is vereist!",
    "invalid_integration": "Deze integratie is niet geldig!",
    "invalid_scaling_mode": null,
    "entity_invalid": {
      "single": null,
      "multiple": null
    }
  },
  "editor": {
    "entity": "Entiteit",
    "integration": "Integratie",
    "required": "Verplicht",
    "recommended": "Aanbevolen",
    "override_headline": "Koptekst overschrijven",
    "hide_when_no_warning": null,
    "hide_caption": null,
    "disable_swiper": null,
    "description": {
      "start": null,
      "current_expected": null,
      "slots": null,
      "separate_events": null,
      "warning_watch_statement": null,
      "end": null
    },
    "error": {
      "expected_entity": null,
      "too_many_entities": null,
      "duplicate": null
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    }
  },
  "events": {
    "no_warnings": "Geen waarschuwingen",
    "nuclear": null,
    "tornado": null,
    "hurricane": null,
    "wind": "wind",
    "earthquake": null,
    "volcano": null,
    "snow_ice": "sneeuw/ijzel/bevriezing",
    "fog": "mist",
    "high_temperature": null,
    "low_temperature": "koude",
    "coastal_event": "kustbedreiging",
    "tsunami": null,
    "sea_event": null,
    "forest_fire": "bos- en heidebranden",
    "avalanches": "lawines",
    "thunderstorms": "onweer",
    "rain": "regen",
    "flooding": null,
    "air_quality": null,
    "dust": null
  },
  "messages": {
    "yellow": {
      "event": "Waarschuwing geel {event}",
      "generic": null,
      "color": null
    },
    "orange": {
      "event": "Waarschuwing oranje {event}",
      "generic": null,
      "color": null
    },
    "red": {
      "event": "Waarschuwing rood {event}",
      "generic": null,
      "color": null
    }
  }
}

=== MrBartusek/MeteoalarmCard/src/localize/languages/en.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Meteoalarm Card",
    "description": "Meteoalarm card warns you about current weather events.",
    "warning": "Warning",
    "expected": "Expected",
    "unavailable": {
      "long": "Integration is unavailable",
      "short": "Unavailable"
    }
  },
  "error": {
    "missing_entity": "Specifying entities is required!",
    "invalid_integration": "This integration is not valid!",
    "invalid_scaling_mode": "This scaling mode is not valid!",
    "entity_invalid": {
      "single": "Selected integration doesn't match selected entity.",
      "multiple": "Selected integration doesn't match selected entities: {entity}."
    }
  },
  "editor": {
    "entity": "Entity",
    "integration": "Integration",
    "required": "Required",
    "recommended": "Recommended",
    "override_headline": "Override headline provided by integration",
    "hide_when_no_warning": "Hide when there are no warnings",
    "hide_caption": "Hide caption",
    "disable_swiper": "Disable alerts swiper",
    "description": {
      "start": "Selected integration creates multiple entities.",
      "current_expected": "First one with the current events and the second one with future ones.",
      "slots": "The exact amount of them created is determined by it's configuration.",
      "separate_events": "Each event kind has a separate entity.",
      "warning_watch_statement": "There are 3 entities: warnings, watches and statements.",
      "end": "You should add all of them to make sure you don't miss any alerts."
    },
    "error": {
      "expected_entity": "Expected warnings entity haven't been provided. Future event won't be shown.",
      "too_many_entities": "More entities than expected haven't been provided. Expected {expected} entities, got {got} entities.",
      "duplicate": "Found duplicates in entities list."
    },
    "scaling_mode": "Scaling Mode",
    "scaling_mode_options": {
      "disabled": "Disabled",
      "headline": "Headline Only",
      "scale": "Scale Only",
      "headline_and_scale": "Headline and scale"
    }
  },
  "events": {
    "no_warnings": "No warnings",
    "nuclear": "nuclear event",
    "tornado": "tornado",
    "hurricane": "hurricane",
    "wind": "wind",
    "earthquake": "earthquake",
    "volcano": "volcano",
    "snow_ice": "snow/ice",
    "fog": "fog",
    "high_temperature": "high temperature",
    "low_temperature": "low temperature",
    "coastal_event": "coastal event",
    "tsunami": "tsunami",
    "sea_event": "sea event",
    "forest_fire": "forest fire",
    "avalanches": "avalanches",
    "thunderstorms": "thunderstorms",
    "rain": "rain",
    "flooding": "flooding",
    "air_quality": "air quality",
    "dust": "dust"
  },
  "messages": {
    "yellow": {
      "event": "Yellow {event} warning",
      "generic": "Yellow warning",
      "color": "Yellow"
    },
    "orange": {
      "event": "Orange {event} warning",
      "generic": "Orange warning",
      "color": "Orange"
    },
    "red": {
      "event": "Red {event} warning",
      "generic": "Red warning",
      "color": "Red"
    }
  }
}

=== MrBartusek/MeteoalarmCard/src/localize/languages/sk.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Meteoalarm Card",
    "description": "Karta Meteoalarm vás upozorní na aktuálne udalosti počasia.",
    "warning": "Varovanie",
    "expected": "Očakavanie",
    "unavailable": {
      "long": "Integrácia nie je k dispozícii",
      "short": "Nedostupné"
    }
  },
  "error": {
    "missing_entity": "Je potrebné zadať entitu!",
    "invalid_integration": "Táto integrácia nie je platná!",
    "invalid_scaling_mode": null,
    "entity_invalid": {
      "single": "Vybratá integrácia sa nezhoduje s vybratou entitou.",
      "multiple": "Vybratá integrácia sa nezhoduje s vybratými entitami: {entity}."
    }
  },
  "editor": {
    "entity": "Entity",
    "integration": "Integrácia",
    "required": "Požadovaný",
    "recommended": "Odporúčané",
    "override_headline": "Prepísať nadpis",
    "hide_when_no_warning": "Skryť, keď nie sú žiadne upozornenia",
    "hide_caption": "Skryť popis",
    "disable_swiper": "Zakázať posúvanie upozornení",
    "description": {
      "start": "Zvolená integrácia vytvára viacero entít.",
      "current_expected": "Prvý s aktuálnymi udalosťami a druhý s budúcimi",
      "slots": "Ich presné množstvo je určené jeho konfiguráciou.",
      "separate_events": "Každý druh udalosti má samostatnú entitu.",
      "warning_watch_statement": "Existujú 3 entity: varovania, stráženia a vyhlásenia.",
      "end": "Mali by ste ich pridať všetky, aby ste sa uistili, že vám žiadne upozornenia neuniknú."
    },
    "error": {
      "expected_entity": "Nebola poskytnutá entita očakávaných upozornení. Budúca udalosť sa nebude zobrazovať.",
      "too_many_entities": "Nebolo poskytnutých viac entít, ako sa očakávalo. Očakávaných entít: {expected}, počet entít: {got}.",
      "duplicate": "V zozname entít sa našli duplikáty."
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    }
  },
  "events": {
    "no_warnings": "Žiadne upozornenia",
    "nuclear": "jadrová udalosť",
    "tornado": "tornádo",
    "hurricane": "hurikán",
    "wind": "vietor",
    "earthquake": "zemetrasenie",
    "volcano": "sopka",
    "snow_ice": "sneh/ľad",
    "fog": "hmla",
    "high_temperature": "vysoká teplota",
    "low_temperature": "nízka teplota",
    "coastal_event": "pobrežná udalosť",
    "tsunami": "cunami",
    "sea_event": "námorná udalosť",
    "forest_fire": "lesný požiar",
    "avalanches": "lavíny",
    "thunderstorms": "búrky",
    "rain": "dážď",
    "flooding": "záplavy",
    "air_quality": "kvalitu ovzdušia",
    "dust": "peľ"
  },
  "messages": {
    "yellow": {
      "event": "Žlté {event} varovanie",
      "generic": "Žlté varovanie",
      "color": "Žlté"
    },
    "orange": {
      "event": "Oranžové {event} varovanie",
      "generic": "Oranžové varovanie",
      "color": "Oranžové"
    },
    "red": {
      "event": "Červené {event} varovanie",
      "generic": "Červené varovanie",
      "color": "Červené"
    }
  }
}

=== MrBartusek/MeteoalarmCard/src/localize/languages/bg.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Meteoalarm Card",
    "description": "Картата Meteoalarm Ви предупреждава за текущите метеорологични събития.",
    "warning": "Предупреждение",
    "expected": "Очаквано",
    "unavailable": {
      "long": "Интеграцията не е достъпна",
      "short": "Недостъпно"
    }
  },
  "error": {
    "missing_entity": "Изисква се посочване на обекти!",
    "invalid_integration": "Тази интеграция не е валидна!",
    "invalid_scaling_mode": null,
    "entity_invalid": {
      "single": "Избраната интеграция не съответства на избрания обект.",
      "multiple": "Избраната интеграция не съответства на избраните обекти: {entity}."
    }
  },
  "editor": {
    "entity": "Обект",
    "integration": "Интеграция",
    "required": "Задължително",
    "recommended": "Препоръчително",
    "override_headline": "Заменете заглавието, предоставено от интеграцията",
    "hide_when_no_warning": "Скриване, когато няма предупреждения",
    "hide_caption": "Скриване на надписа",
    "disable_swiper": "Деактивиране на alerts swiper",
    "description": {
      "start": "Избраната интеграция създава множество обекти.",
      "current_expected": "Първият с текущите събития, а вторият с бъдещите.",
      "slots": "The exact amount of them created is determined by it's configuration.",
      "separate_events": "Всеки вид събитие има отделен обект.",
      "warning_watch_statement": "Има 3 обекта: предупреждения, наблюдения и изявления.",
      "end": "Трябва да добавите всички тях, за да сте сигурни, че няма да пропуснете никакви сигнали."
    },
    "error": {
      "expected_entity": "Expected warnings entity haven't been provided. Future event won't be shown.",
      "too_many_entities": "More entities than expected haven't been provided. Expected {expected} entities, got {got} entities.",
      "duplicate": "Открити са дубликати в списъка с обекти."
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    }
  },
  "events": {
    "no_warnings": "Без опасни явления",
    "nuclear": "ядрено събитие",
    "tornado": "торнадо",
    "hurricane": "ураган",
    "wind": "вятър",
    "earthquake": "земетресение",
    "volcano": "вулкан",
    "snow_ice": "сняг/поледица",
    "fog": "мъгла",
    "high_temperature": "високи температури",
    "low_temperature": "ниски температури",
    "coastal_event": "крайбрежно събитие",
    "tsunami": "цунами",
    "sea_event": "морско събитие",
    "forest_fire": "горски пожари",
    "avalanches": "лавини",
    "thunderstorms": "гръмотевична активност",
    "rain": "дъжд",
    "flooding": "наводнения",
    "air_quality": "качество на въздуха",
    "dust": "прах"
  },
  "messages": {
    "yellow": {
      "event": "Жълт код за {event}",
      "generic": "Жълт код",
      "color": "Жълт"
    },
    "orange": {
      "event": "Оранжев код за {event}",
      "generic": "Оранжев код",
      "color": "Оранжев"
    },
    "red": {
      "event": "Червен код за {event}",
      "generic": "Червен код",
      "color": "Червен"
    }
  }
}
